### ISSUE TITLE
Failing Ad-Hoc task on Moodle 3.7

### ISSUE THREAD

**Issue by aspark21** [blackboard-open-source/moodle-mod_collaborate#9]
Moodle 3.7.1
Master branch 

Adhoc task failed: core_course\task\course_delete_modules,Coding error detected, it must be fixed by a programmer: The course module 1108455 could not be deleted. #0 /pathtomoodle/mod/collaborate/classes/sessionlink.php(335): moodle_database->get_in_or_equal(Array)

#1 /pathtomoodle/mod/collaborate/classes/sessionlink.php(376): mod_collaborate\sessionlink::attempt_delete_sessions(Array)

#2 /pathtomoodle/mod/collaborate/lib.php(158): mod_collaborate\sessionlink::delete_sessions('2007')

#3 /pathtomoodle/course/lib.php(1150): collaborate_delete_instance('2007')

#4 /pathtomoodle/course/classes/task/course_delete_modules.php(66): course_delete_module('1108455')

#5 /pathtomoodle/lib/cronlib.php(272): core_course\task\course_delete_modules->execute()

#6 /pathtomoodle/lib/cronlib.php(155): cron_run_inner_adhoc_task(Object(core_course\task\course_delete_modules))

#7 /pathtomoodle/lib/cronlib.php(76): cron_run_adhoc_tasks(1564334682)

#8 /pathtomoodle/admin/cli/cron.php(61): cron_run()

#9 {main}

Backtrace:

* line 272 of /lib/cronlib.php: call to core_course\task\course_delete_modules->execute()

* line 155 of /lib/cronlib.php: call to cron_run_inner_adhoc_task()

* line 76 of /lib/cronlib.php: call to cron_run_adhoc_tasks()

* line 61 of /admin/cli/cron.php: call to cron_run()

**Comment by aspark21** [comment]
Execute scheduled task: Clean up sessions task (mod_collaborate\task\cleanup_sessions_task)
... used 2 dbqueries
... used 0.55186700820923 seconds
Scheduled task failed: Clean up sessions task (mod_collaborate\task\cleanup_sessions_task),Coding error detected, it must be fixed by a programmer: moodle_database::get_in_or_equal() does not accept empty array

**Comment by aspark21** [comment]
Great to see the complete lack of interest in resolving this @ jgg9026

**Comment by MURBASLMS** [comment]
Hi, has anyone resolved this? we still get the error, i suspect because older courses have been restored into moodle with soap remnants. Any way to clean this up as this task keeps failing - cheers

**Comment by MURBASLMS** [comment]
on 3.9 branch btw
